source 'https://rubygems.org'

gem 'spring'
gem 'jazz_hands'
gem 'railroady'

gem 'rails', '4.0.4'

gem 'sqlite3'
gem 'uglifier', '>= 2.5.0'
gem 'twitter'
gem 'awesome_print'
gem 'grape'
gem 'kaminari'
gem 'sass-rails'
gem 'compass-rails'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :doc do
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
